name: codementor_ai
description: Mobile learning app for programming with AI mentor elements.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
